import Head from 'next/head'
import React from 'react'
export default function HeadHtml() {
    return (
        <Head>
            <title>Smith Game Shop</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
            <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Patua+One&display=swap" rel="stylesheet" />
        </Head>
    )
}


