import { Html,Head, Main, NextScript } from 'next/document'
export default function Document() {
  return (
    <Html>
        <Head>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
            <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Patua+One&display=swap" rel="stylesheet" />
            {/* <script src="https://apis.google.com/js/platform.js" async defer></script> */}
        </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
